In [44]:
import pandas as pd
import numpy as np

In [2]:
%config Completer.use_jedi = False

In [3]:
usda = pd.read_csv("USDA_Clean.csv", index_col = 0)

In [4]:
usda = usda.drop(columns = ['ID',"Description"])

In [10]:
X = usda['Calories']
Y = usda.drop(columns = ['Calories'])

In [11]:
Y

Protein  TotalFat  Carbohydrate  Sodium  Cholesterol  Sugar  Calcium  \
1        0.85     81.11          0.06     714          215   0.06       24   
2        0.85     81.11          0.06     827          219   0.06       24   
3        0.28     99.48          0.00       2          256   0.00        4   
4       21.40     28.74          2.34    1395           75   0.50      528   
5       23.24     29.68          2.79     560           94   0.51      674   
...       ...       ...           ...     ...          ...    ...      ...   
7053    16.40      0.30          0.00      58           50   0.00       18   
7054    18.50     25.10          0.00    4450           95   0.00       66   
7055    20.54      0.84          5.41     667           41   0.00       10   
7056    16.10      1.40          2.00      70           50   0.00       10   
7057    19.80      0.50          0.00      68           50   0.00      118   

      Iron  Potassium  VitaminC  VitaminE  VitaminD  HighSodium  HighCals  \
1     0.02         24       0.0      2.32       1.5           1         1   
2     0.16         26       0.0      2.32       1.5           1         1   
3     0.00          5       0.0      2.80       1.8           0         1   
4     0.31        256       0.0      0.25       0.5           1         1   
5     0.43        136       0.0      0.26       0.5           1         1   
...    ...        ...       ...       ...       ...         ...       ...   
7053  1.50        285       0.0      1.00       0.2           0         0   
7054  1.40        520       0.0      2.38      25.2           1         1   
7055  0.58        314       0.0      0.00       0.0           1         0   
7056  3.50        382       0.0      5.00       0.0           0         0   
7057  1.40        230       0.0      0.50       0.0           0         0   

      HighSugar  HighProtein  HighFat  
1             0            0        1  
2             0            0        1  
3             0            0        1  
4             0            1        1  
5             0            1        1  
...         ...          ...      ...  
7053          0            1        0  
7054          0            1        1  
7055          0            1        0  
7056          0            1        0  
7057          0            1        0  

[6310 rows x 17 columns]

In [13]:
X = usda[['Calories']]
X

Calories
1          717
2          717
3          876
4          353
5          371
...        ...
7053        73
7054       305
7055       111
7056        90
7057        89

[6310 rows x 1 columns]

In [19]:
Y.to_numpy().shape

(6310, 17)

In [15]:
X.to_numpy().shape

(6310, 1)

In [4]:
df = pd.DataFrame({
        "x1": [1, 2, 3],
        "x2": [4, 5, 6],
        "y": ["a", "b", "c"]  # Invalid target (strings instead of numbers)
    })

In [5]:
df

x1  x2  y
0   1   4  a
1   2   5  b
2   3   6  c

In [22]:
y = df[["y"]].to_numpy()

ValueError: could not convert string to float: 'a'

In [15]:
y.dtype == np.float64 

False

In [21]:
X = df[["x1","x2"]]

In [23]:
df.isnumeric()

AttributeError: 'DataFrame' object has no attribute 'isnumeric'

In [19]:
X.dtype

dtype('int64')

In [27]:
X = np.matrix([[1  ,1,  2],
 [1 , 2 , 1],
 [1 , 3 , 0],
 [1  ,4 ,-1]])

In [31]:
Y = np.matrix(np.array([13,12,11,10]).reshape(4,1))

In [33]:
XT = X

(matrix([[ 1,  1,  2],
         [ 1,  2,  1],
         [ 1,  3,  0],
         [ 1,  4, -1]]),
 matrix([[13],
         [12],
         [11],
         [10]]))

In [46]:
XT = X.transpose()
XT

matrix([[ 1,  1,  1,  1],
        [ 1,  2,  3,  4],
        [ 2,  1,  0, -1]])

In [52]:
XTX = XT*X
XTX

matrix([[ 4, 10,  2],
        [10, 30,  0],
        [ 2,  0,  6]])

In [54]:
np.linalg.matrix_rank(X)

np.int64(2)

In [40]:
inv*X.transpose()*Y

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [49]:
df = pd.DataFrame({
        "x1": [1, 2, 3, 4],
        "x2": [2, 1, 0, -1]
    })
y = 2 + 3 * df["x1"] + 4 * df["x2"]
df["y"] = y


In [50]:
df

x1  x2   y
0   1   2  13
1   2   1  12
2   3   0  11
3   4  -1  10